#! /usr/bin/zsh

brew tap "homebrew/bundle"
brew tap "homebrew/cask"
brew tap "homebrew/cask-drivers"
brew tap "homebrew/cask-versions"
brew tap "homebrew/core"
brew tap "homebrew/services"

brew install "bash-completion"
brew install "coreutils"
brew install "readline"
brew install "python"
brew install "findutils"
brew install "git-extras"
brew install "gnu-sed"
brew install "grep"
brew install "highlight"
brew install "hub"
brew install "mas"
brew install "node"
brew install "shellcheck"
brew install "thefuck"
brew install "wget"
brew install "yarn"

brew cask install "1password"
brew cask install "alfred"
brew cask install "bartender"
brew cask install "bettertouchtool"
brew cask install "betterzip"
brew cask install "box-sync"
brew cask install "dropbox"
brew cask install "forklift"
brew cask install "gitkraken"
brew cask install "google-chrome"
brew cask install "iterm2"
brew cask install "qladdict"
brew cask install "qlcolorcode"
brew cask install "qlimagesize"
brew cask install "qlmarkdown"
brew cask install "qlstephen"
brew cask install "qlvideo"
brew cask install "quicklook-csv"
brew cask install "quicklook-json"
brew cask install "quicklookase"
brew cask install "visual-studio-code"

mas install 577085396 # Unclutter
mas install 497799835 # Xcode